server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-Url:
      defaultZone: http://localhost:8088/eureka/
spring:
  application:
   name: product
  datasource:
    name: sell
    url:  jdbc:mysql://localhost:3306/sell?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

